#!/usr/bin/env python3

import requests
import yaml
import time
from collections import defaultdict
from datetime import datetime, timezone
from typing import Dict, List

# List of URLs to process
URLs = [
"https://artifacthub.io/api/v1/packages/helm/adfinis/keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/aerospike/aerospike-kubernetes-operator",
"https://artifacthub.io/api/v1/packages/helm/agentkube-operator/agentkube-operator",
"https://artifacthub.io/api/v1/packages/helm/aistore/ais-operator",
"https://artifacthub.io/api/v1/packages/helm/alekc/gitlab-runner-operator",
"https://artifacthub.io/api/v1/packages/helm/alekc/rabbitmq-cluster-operator",
"https://artifacthub.io/api/v1/packages/helm/altinity-clickhouse-operator/altinity-clickhouse-operator",
"https://artifacthub.io/api/v1/packages/helm/apache-flink-kubernetes/flink-kubernetes-operator",
"https://artifacthub.io/api/v1/packages/helm/apache-solr/solr-operator",
"https://artifacthub.io/api/v1/packages/helm/appscode/capa-vpc-peering-operator",
"https://artifacthub.io/api/v1/packages/helm/appscode/docker-machine-operator",
"https://artifacthub.io/api/v1/packages/helm/appscode/external-dns-operator",
"https://artifacthub.io/api/v1/packages/helm/appscode/grafana-operator",
"https://artifacthub.io/api/v1/packages/helm/appscode/kubepack-operator",
"https://artifacthub.io/api/v1/packages/helm/appscode/kubestash-operator",
"https://artifacthub.io/api/v1/packages/helm/appscode/kubevault-operator",
"https://artifacthub.io/api/v1/packages/helm/appscode/monitoring-operator",
"https://artifacthub.io/api/v1/packages/helm/appscode/operator-shard-manager",
"https://artifacthub.io/api/v1/packages/helm/appscode/prometheus-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/appscode/vault-operator",
"https://artifacthub.io/api/v1/packages/helm/appuio/stardog-userrole-operator",
"https://artifacthub.io/api/v1/packages/helm/argocd-rbac-operator/argocd-rbac-operator",
"https://artifacthub.io/api/v1/packages/helm/arldka/prometheus-operated",
"https://artifacthub.io/api/v1/packages/helm/arldka/prometheus-operator",
"https://artifacthub.io/api/v1/packages/helm/armory/armory-spinnaker-operator",
"https://artifacthub.io/api/v1/packages/helm/arzu/postgres-operator",
"https://artifacthub.io/api/v1/packages/helm/astarte/astarte-operator",
"https://artifacthub.io/api/v1/packages/helm/awx-operator-helm/awx-operator",
"https://artifacthub.io/api/v1/packages/helm/axonops-developer-operator/axonops-developer-operator",
"https://artifacthub.io/api/v1/packages/helm/azure-sample/tweet-factory-operator",
"https://artifacthub.io/api/v1/packages/helm/backblaze-operator/backblaze-operator",
"https://artifacthub.io/api/v1/packages/helm/backlokto/backlokto-operator",
"https://artifacthub.io/api/v1/packages/helm/backube-helm-charts/scribe",
"https://artifacthub.io/api/v1/packages/helm/backube-helm-charts/snapscheduler",
"https://artifacthub.io/api/v1/packages/helm/backube-helm-charts/volsync",
"https://artifacthub.io/api/v1/packages/helm/backup-operator/backup-operator",
"https://artifacthub.io/api/v1/packages/helm/bakito/k8s-event-logger-operator",
"https://artifacthub.io/api/v1/packages/helm/baler-operator/baler-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/backyards-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/canary-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/dast-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/etcd-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/grafana-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/integrated-service-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/istio-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/istio-release-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/kafka-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/logging-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/logging-operator-fluent",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/logging-operator-logging",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/mysql-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/nodepool-labels-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/prometheus-operator-standalone",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/pvc-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/thanos-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/vault-operator",
"https://artifacthub.io/api/v1/packages/helm/banzaicloud-stable/zookeeper-operator",
"https://artifacthub.io/api/v1/packages/helm/beezlabs/cloudflare-tunnel-operator",
"https://artifacthub.io/api/v1/packages/helm/beryju-org/trident-operator",
"https://artifacthub.io/api/v1/packages/helm/bitnami-aks/contour-operator",
"https://artifacthub.io/api/v1/packages/helm/bitnami-aks/grafana-operator",
"https://artifacthub.io/api/v1/packages/helm/bitnami-aks/prometheus-operator",
"https://artifacthub.io/api/v1/packages/helm/bitnami-aks/rabbitmq-cluster-operator",
"https://artifacthub.io/api/v1/packages/helm/bitnami/clickhouse-operator",
"https://artifacthub.io/api/v1/packages/helm/bitnami/grafana-k6-operator",
"https://artifacthub.io/api/v1/packages/helm/bitnami/grafana-operator",
"https://artifacthub.io/api/v1/packages/helm/bitnami/minio-operator",
"https://artifacthub.io/api/v1/packages/helm/bitnami/rabbitmq-cluster-operator",
"https://artifacthub.io/api/v1/packages/helm/bitpoke/bitpoke",
"https://artifacthub.io/api/v1/packages/helm/bitpoke/mysql-operator",
"https://artifacthub.io/api/v1/packages/helm/bitpoke/stack",
"https://artifacthub.io/api/v1/packages/helm/bitpoke/wordpress-operator",
"https://artifacthub.io/api/v1/packages/helm/bitwarden/sm-operator",
"https://artifacthub.io/api/v1/packages/helm/book-k8sinfra-v2/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/bottlerocket-update-operator/bottlerocket-update-operator",
"https://artifacthub.io/api/v1/packages/helm/bougoucharts/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/btungut/kubernetes-azure-keyvault-secret-operator",
"https://artifacthub.io/api/v1/packages/helm/buttahtoast/kubermatic-operator",
"https://artifacthub.io/api/v1/packages/helm/bytebuilders/vault-operator-community",
"https://artifacthub.io/api/v1/packages/helm/camptocamp3/prometheus-operator",
"https://artifacthub.io/api/v1/packages/helm/camptocamp3/prometheus-operator-csv",
"https://artifacthub.io/api/v1/packages/helm/camptocamp3/redisoperator",
"https://artifacthub.io/api/v1/packages/helm/capsule/capsule",
"https://artifacthub.io/api/v1/packages/helm/capsule-proxy/capsule-proxy",
"https://artifacthub.io/api/v1/packages/helm/casdoor-operator/casdoor-operator",
"https://artifacthub.io/api/v1/packages/helm/ccowley/mongodb-operator",
"https://artifacthub.io/api/v1/packages/helm/cert-utils-operator/cert-utils-operator",
"https://artifacthub.io/api/v1/packages/helm/chaosblade-operator/chaosblade-operator",
"https://artifacthub.io/api/v1/packages/helm/chaos-mesh/chaos-mesh",
"https://artifacthub.io/api/v1/packages/helm/ckotzbauer/postgres-operator",
"https://artifacthub.io/api/v1/packages/helm/ckotzbauer/sbom-operator",
"https://artifacthub.io/api/v1/packages/helm/ckotzbauer/vulnerability-operator",
"https://artifacthub.io/api/v1/packages/helm/clastix/kamaji-etcd",
"https://artifacthub.io/api/v1/packages/helm/cloudcioperator/cloudcioperator",
"https://artifacthub.io/api/v1/packages/helm/cloudflare-tunnel-ingress-controller/cloudflare-tunnel-ingress-controller",
"https://artifacthub.io/api/v1/packages/helm/cloudnativeapp/etcd-operator",
"https://artifacthub.io/api/v1/packages/helm/cloudnativeapp/jaeger-operator",
"https://artifacthub.io/api/v1/packages/helm/cloudnativeapp/jenkins-operator",
"https://artifacthub.io/api/v1/packages/helm/cloudnativeapp/kanister-operator",
"https://artifacthub.io/api/v1/packages/helm/cloudnativeapp/prometheus-operator",
"https://artifacthub.io/api/v1/packages/helm/cloudnativeapp/sparkoperator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/argocd-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/elasticsearch-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/gitea-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/grafana-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-ace-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-apic-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-aspera-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-assetrepository-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-automation-foundation-core-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibmcloud-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-cp4a-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-cp4i-operators",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-cp4s-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-cpd-platform-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-cpd-scheduling-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-datapower-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-db2u-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-eventstreams-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-mq-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-opsdashboard-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ibm-process-mining-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/instana-agent-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/jaeger-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/kiali-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/nexus-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/oadp-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/ocs-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/odf-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/sealed-secrets-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/serverless-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/service-mesh-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/spp-operator",
"https://artifacthub.io/api/v1/packages/helm/cloud-native-toolkit/tekton-operator",
"https://artifacthub.io/api/v1/packages/helm/cloudposse/prometheus-operator",
"https://artifacthub.io/api/v1/packages/helm/cloudposse/service-level-operator",
"https://artifacthub.io/api/v1/packages/helm/cluster-api-operator/cluster-api-operator",
"https://artifacthub.io/api/v1/packages/helm/cluster-network-policy-operator/cluster-network-policy-operator",
"https://artifacthub.io/api/v1/packages/helm/cmak-operator/cmak-operator",
"https://artifacthub.io/api/v1/packages/helm/commonground/postgres-operator",
"https://artifacthub.io/api/v1/packages/helm/commonground/postgres-operator-ui",
"https://artifacthub.io/api/v1/packages/helm/community-operator-v2/community-operator-v2",
"https://artifacthub.io/api/v1/packages/helm/containeroo/cloudflare-operator",
"https://artifacthub.io/api/v1/packages/helm/couchbase/couchbase-operator",
"https://artifacthub.io/api/v1/packages/helm/cowboysysop/mpi-operator",
"https://artifacthub.io/api/v1/packages/helm/cowboysysop/training-operator",
"https://artifacthub.io/api/v1/packages/helm/craftypath/sops-operator",
"https://artifacthub.io/api/v1/packages/helm/crashloop-operator/crashloop-operator",
"https://artifacthub.io/api/v1/packages/helm/crowdfox/external-service-operator",
"https://artifacthub.io/api/v1/packages/helm/cyphernetes-operator/cyphernetes-operator",
"https://artifacthub.io/api/v1/packages/helm/dash0-operator/dash0-operator",
"https://artifacthub.io/api/v1/packages/helm/dask/dask-kubernetes-operator",
"https://artifacthub.io/api/v1/packages/helm/datadog/datadog-operator",
"https://artifacthub.io/api/v1/packages/helm/datadog-test/datadog-operator",
"https://artifacthub.io/api/v1/packages/helm/datawire/ambassador-operator",
"https://artifacthub.io/api/v1/packages/helm/dbman/dbman",
"https://artifacthub.io/api/v1/packages/helm/db-operator/db-operator",
"https://artifacthub.io/api/v1/packages/helm/db-operator-ng/db-operator",
"https://artifacthub.io/api/v1/packages/helm/developer-operator/developer-operator",
"https://artifacthub.io/api/v1/packages/helm/devopstales/trivy-operator",
"https://artifacthub.io/api/v1/packages/helm/devtron/devtron-operator",
"https://artifacthub.io/api/v1/packages/helm/devtron/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/devtron-labs/devtron-operator",
"https://artifacthub.io/api/v1/packages/helm/devtron-labs/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/divistant/jobs",
"https://artifacthub.io/api/v1/packages/helm/doris/doris-operator",
"https://artifacthub.io/api/v1/packages/helm/dtrdnk-helm-charts/tempo-operator",
"https://artifacthub.io/api/v1/packages/helm/dyff-operator/dyff-operator",
"https://artifacthub.io/api/v1/packages/helm/dynatrace/dynatrace-operator",
"https://artifacthub.io/api/v1/packages/helm/eclipse-che/eclipse-che",
"https://artifacthub.io/api/v1/packages/helm/eg-universal-agent-operator/eg-universal-agent-operator",
"https://artifacthub.io/api/v1/packages/helm/elastic/eck-operator",
"https://artifacthub.io/api/v1/packages/helm/elastic/eck-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/emqx-operator/edge-operator",
"https://artifacthub.io/api/v1/packages/helm/emqx-operator/emqx-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/admin-console-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/cd-pipeline-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/codebase-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp-dev/cd-pipeline-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp-dev/codebase-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp-dev/edp-headlamp",
"https://artifacthub.io/api/v1/packages/helm/epmdedp-dev/edp-install",
"https://artifacthub.io/api/v1/packages/helm/epmdedp-dev/gerrit-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp-dev/jenkins-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp-dev/keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp-dev/nexus-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp-dev/sonar-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp-dev/tekton-custom-task",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/edp-argocd-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/edp-component-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/edp-headlamp",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/edp-install",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/gerrit-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/jenkins-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/nexus-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/perf-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/reconciler",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/sonar-operator",
"https://artifacthub.io/api/v1/packages/helm/epmdedp/tekton-custom-task",
"https://artifacthub.io/api/v1/packages/helm/evryfs-oss/github-actions-runner-operator",
"https://artifacthub.io/api/v1/packages/helm/ext-postgres-operator/ext-postgres-operator",
"https://artifacthub.io/api/v1/packages/helm/flink-operator/flink-operator",
"https://artifacthub.io/api/v1/packages/helm/fluent/fluent-operator",
"https://artifacthub.io/api/v1/packages/helm/fluent-operator/fluent-operator",
"https://artifacthub.io/api/v1/packages/helm/flux-operator/flux-operator",
"https://artifacthub.io/api/v1/packages/helm/flyway-operator/flyway-operator",
"https://artifacthub.io/api/v1/packages/helm/fmjstudios/keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/forked-gpu/gpu-operator",
"https://artifacthub.io/api/v1/packages/helm/frinx-helm-charts/frinx-machine-operators",
"https://artifacthub.io/api/v1/packages/helm/frp/frp-operator",
"https://artifacthub.io/api/v1/packages/helm/frp-operator/frp-operator",
"https://artifacthub.io/api/v1/packages/helm/function-mesh/function-mesh-operator",
"https://artifacthub.io/api/v1/packages/helm/gardener-charts/gardener-operator",
"https://artifacthub.io/api/v1/packages/helm/garge/garge-operator",
"https://artifacthub.io/api/v1/packages/helm/gitlab/gitlab-operator",
"https://artifacthub.io/api/v1/packages/helm/glasskube/glasskube-operator",
"https://artifacthub.io/api/v1/packages/helm/gpg-dev/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/gpg-dev/opentelemetry-operator",
"https://artifacthub.io/api/v1/packages/helm/gpg-dev/prometheus-operator-admission-webhook",
"https://artifacthub.io/api/v1/packages/helm/gpu-operator/gpu-operator",
"https://artifacthub.io/api/v1/packages/helm/gpu-operator/k8s-nim-operator",
"https://artifacthub.io/api/v1/packages/helm/gpu-operator/network-operator",
"https://artifacthub.io/api/v1/packages/helm/grafana/alloy-operator",
"https://artifacthub.io/api/v1/packages/helm/grafana/grafana-agent-operator",
"https://artifacthub.io/api/v1/packages/helm/grafana/grafana-operator",
"https://artifacthub.io/api/v1/packages/helm/grafana/k6-operator",
"https://artifacthub.io/api/v1/packages/helm/grafana/rollout-operator",
"https://artifacthub.io/api/v1/packages/helm/grdscloud/backup-operator",
"https://artifacthub.io/api/v1/packages/helm/grdscloud/mysql-operator",
"https://artifacthub.io/api/v1/packages/helm/gresearch/armada-operator",
"https://artifacthub.io/api/v1/packages/helm/hadron-operator/hadron-operator",
"https://artifacthub.io/api/v1/packages/helm/hashicorp/hcp-terraform-operator",
"https://artifacthub.io/api/v1/packages/helm/hashicorp/terraform-cloud-operator",
"https://artifacthub.io/api/v1/packages/helm/hashicorp/vault-secrets-operator",
"https://artifacthub.io/api/v1/packages/helm/haukitech/prometheus-operator",
"https://artifacthub.io/api/v1/packages/helm/hazelcast/hazelcast-platform-operator",
"https://artifacthub.io/api/v1/packages/helm/hazelcast/hazelcast-platform-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/helm-charts/ditto-operator",
"https://artifacthub.io/api/v1/packages/helm/helm-charts/hawkbit-operator",
"https://artifacthub.io/api/v1/packages/helm/helm-monitorie/helm-monitorie",
"https://artifacthub.io/api/v1/packages/helm/helm-operator/helm-operator",
"https://artifacthub.io/api/v1/packages/helm/helm-postgres-kubegres/postgres-with-operator",
"https://artifacthub.io/api/v1/packages/helm/helm-snowplow/helm-snowplow",
"https://artifacthub.io/api/v1/packages/helm/hivemq/hivemq-operator",
"https://artifacthub.io/api/v1/packages/helm/hivemq/hivemq-platform-operator",
"https://artifacthub.io/api/v1/packages/helm/hkube/etcd-operator",
"https://artifacthub.io/api/v1/packages/helm/homer-operator/homer-operator",
"https://artifacthub.io/api/v1/packages/helm/hpcr-operator/k8s-operator-hpcr",
"https://artifacthub.io/api/v1/packages/helm/ibm-charts/data-exhaust-crd-operator-chart",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-appconnect-operator",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-cert-manager-operator",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-cert-manager-operator-cluster-scoped",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-common-service-operator",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-common-service-operator-cluster-scoped",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-commonui-operator-app",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-commonui-operator-app-cluster-scoped",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-eem-operator",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-eem-operator-crd",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-ep-operator",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-ep-operator-crd",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-eventautomation-flink-operator",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-eventautomation-flink-operator-crd",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-eventstreams-operator",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-iam-operator",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-iam-operator-cluster-scoped",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-namespace-scope-operator",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-namespace-scope-operator-cluster-scoped",
"https://artifacthub.io/api/v1/packages/helm/ibm-helm/ibm-operator-catalog-enablement",
"https://artifacthub.io/api/v1/packages/helm/inaccel/fpga-operator",
"https://artifacthub.io/api/v1/packages/helm/infisical/secrets-operator",
"https://artifacthub.io/api/v1/packages/helm/influxdata/telegraf-operator",
"https://artifacthub.io/api/v1/packages/helm/inlets/inlets-operator",
"https://artifacthub.io/api/v1/packages/helm/intel/intel-device-plugins-operator",
"https://artifacthub.io/api/v1/packages/helm/istio/operator",
"https://artifacthub.io/api/v1/packages/helm/istio-ratelimit-operator/istio-ratelimit-operator",
"https://artifacthub.io/api/v1/packages/helm/itscontained/secret-manager",
"https://artifacthub.io/api/v1/packages/helm/jacobcolvin/dragonfly-operator",
"https://artifacthub.io/api/v1/packages/helm/jacobcolvin/tailscale-operator",
"https://artifacthub.io/api/v1/packages/helm/jacobcolvin/wireguard-operator",
"https://artifacthub.io/api/v1/packages/helm/jaegertracing/jaeger-operator",
"https://artifacthub.io/api/v1/packages/helm/jenkins/jenkins-operator",
"https://artifacthub.io/api/v1/packages/helm/jenkins-x/sso-operator",
"https://artifacthub.io/api/v1/packages/helm/jenkins-x/vault-operator",
"https://artifacthub.io/api/v1/packages/helm/jetic-operator/jetic-operator",
"https://artifacthub.io/api/v1/packages/helm/jfrog/jfrog-registry-operator",
"https://artifacthub.io/api/v1/packages/helm/k8gb/k8gb",
"https://artifacthub.io/api/v1/packages/helm/k8s-event-logger-operator-oci/k8s-event-logger-operator",
"https://artifacthub.io/api/v1/packages/helm/k8sgpt/k8sgpt-operator",
"https://artifacthub.io/api/v1/packages/helm/k8s-jacoco-operator/k8s-jacoco-operator",
"https://artifacthub.io/api/v1/packages/helm/k8ssandra/cass-operator",
"https://artifacthub.io/api/v1/packages/helm/k8ssandra/k8ssandra-operator",
"https://artifacthub.io/api/v1/packages/helm/kafka-schema-operator/kafka-schema-operator",
"https://artifacthub.io/api/v1/packages/helm/kaiso/kom-operator",
"https://artifacthub.io/api/v1/packages/helm/kanister/kanister-operator",
"https://artifacthub.io/api/v1/packages/helm/karbonite/karbonite",
"https://artifacthub.io/api/v1/packages/helm/keycloak-client-operator/keycloak-client-operator",
"https://artifacthub.io/api/v1/packages/helm/keycloak-operator-by-kubitus-project/keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/keycloak-operator/keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/keycloak-operator-legacy/keycloak-operator-legacy",
"https://artifacthub.io/api/v1/packages/helm/keyporttech/helm-mongodb-operator",
"https://artifacthub.io/api/v1/packages/helm/kiali/kiali-operator",
"https://artifacthub.io/api/v1/packages/helm/kloudlite/kloudlite-platform-operator",
"https://artifacthub.io/api/v1/packages/helm/kompost/kompost",
"https://artifacthub.io/api/v1/packages/helm/kong/gateway-operator",
"https://artifacthub.io/api/v1/packages/helm/kong/kong-operator",
"https://artifacthub.io/api/v1/packages/helm/koordinator/koordinator-yarn-operator",
"https://artifacthub.io/api/v1/packages/helm/krateo/crate-operator",
"https://artifacthub.io/api/v1/packages/helm/krateo/crate-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/krateo/finops-operator-exporter",
"https://artifacthub.io/api/v1/packages/helm/krateo/finops-operator-focus",
"https://artifacthub.io/api/v1/packages/helm/krateo/finops-operator-scraper",
"https://artifacthub.io/api/v1/packages/helm/krateo/finops-operator-vm-manager",
"https://artifacthub.io/api/v1/packages/helm/kronos-core/kronos-core",
"https://artifacthub.io/api/v1/packages/helm/kuadrant/authorino-operator",
"https://artifacthub.io/api/v1/packages/helm/kuadrant/dns-operator",
"https://artifacthub.io/api/v1/packages/helm/kuadrant/kuadrant-operator",
"https://artifacthub.io/api/v1/packages/helm/kuadrant/limitador-operator",
"https://artifacthub.io/api/v1/packages/helm/kubearmor/kubearmor-operator",
"https://artifacthub.io/api/v1/packages/helm/kubebb/fabric-operator",
"https://artifacthub.io/api/v1/packages/helm/kubebb/tekton-operator",
"https://artifacthub.io/api/v1/packages/helm/kubeblocks/chaos-mesh",
"https://artifacthub.io/api/v1/packages/helm/kubeblocks/cubetran",
"https://artifacthub.io/api/v1/packages/helm/kubeblocks/dt-platform",
"https://artifacthub.io/api/v1/packages/helm/kubeblocks/kubeblocks",
"https://artifacthub.io/api/v1/packages/helm/kubeblocks/kubetran",
"https://artifacthub.io/api/v1/packages/helm/kubeblocks/postgres-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/airflow-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/commons-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/dolphinscheduler-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/hbase-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/hdfs-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/hive-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/kafka-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/listener-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/secret-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/spark-k8s-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/superset-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/trino-operator",
"https://artifacthub.io/api/v1/packages/helm/kubedoop/zookeeper-operator",
"https://artifacthub.io/api/v1/packages/helm/kube-ecr-secrets-operator/kube-ecr-secrets-operator",
"https://artifacthub.io/api/v1/packages/helm/kubegems/function-mesh-operator",
"https://artifacthub.io/api/v1/packages/helm/kubegems/intel-device-operator",
"https://artifacthub.io/api/v1/packages/helm/kubegems/logging-operator",
"https://artifacthub.io/api/v1/packages/helm/kubegems/pulsar-operator",
"https://artifacthub.io/api/v1/packages/helm/kubegems/seldon-core-operator",
"https://artifacthub.io/api/v1/packages/helm/kube-logging/logging-operator",
"https://artifacthub.io/api/v1/packages/helm/kube-logging/logging-operator-logging",
"https://artifacthub.io/api/v1/packages/helm/kube-prometheus-stack-oci/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/kuberay-operator/kuberay-operator",
"https://artifacthub.io/api/v1/packages/helm/kubernetes-dbaas/kubernetes-dbaas",
"https://artifacthub.io/api/v1/packages/helm/kubernetes-replicator/brudi-operator",
"https://artifacthub.io/api/v1/packages/helm/kubernetes-replicator/harbor-operator",
"https://artifacthub.io/api/v1/packages/helm/kubescape/kubescape-cloud-operator",
"https://artifacthub.io/api/v1/packages/helm/kubescape/kubescape-operator",
"https://artifacthub.io/api/v1/packages/helm/kubeshop/testkube-operator",
"https://artifacthub.io/api/v1/packages/helm/kubesphere/fluentbit-operator",
"https://artifacthub.io/api/v1/packages/helm/kubesphere-stable/chaos-mesh",
"https://artifacthub.io/api/v1/packages/helm/kubesphere-stable/fpga-operator",
"https://artifacthub.io/api/v1/packages/helm/kubesphere-stable/qiming-operator",
"https://artifacthub.io/api/v1/packages/helm/kube-starrocks/operator",
"https://artifacthub.io/api/v1/packages/helm/kubevious/workload-operator",
"https://artifacthub.io/api/v1/packages/helm/kusionstack/sample-operator",
"https://artifacthub.io/api/v1/packages/helm/kvalitetsit/dynatrace-operator",
"https://artifacthub.io/api/v1/packages/helm/kvalitetsit/strimzi-kafka-operator",
"https://artifacthub.io/api/v1/packages/helm/kyverno-nirmata/enterprise-kyverno-operator",
"https://artifacthub.io/api/v1/packages/helm/kyverno-nirmata/kyverno-operator",
"https://artifacthub.io/api/v1/packages/helm/kyverno-nirmata/nirmata-kyverno-operator",
"https://artifacthub.io/api/v1/packages/helm/kyverno-nirmata/nirmata-kyverno-operator-crd",
"https://artifacthub.io/api/v1/packages/helm/lerentis/bitwarden-crd-operator",
"https://artifacthub.io/api/v1/packages/helm/lifecycle-toolkit/keptn",
"https://artifacthub.io/api/v1/packages/helm/lifecycle-toolkit/keptn-cert-manager",
"https://artifacthub.io/api/v1/packages/helm/lifecycle-toolkit/keptn-lifecycle-operator",
"https://artifacthub.io/api/v1/packages/helm/lifecycle-toolkit/keptn-metrics-operator",
"https://artifacthub.io/api/v1/packages/helm/lifecycle-toolkit/klt",
"https://artifacthub.io/api/v1/packages/helm/lightrun-k8s-operator/lightrun-k8s-operator",
"https://artifacthub.io/api/v1/packages/helm/loafoe/patch-operator",
"https://artifacthub.io/api/v1/packages/helm/loft/vcluster-pro-operator",
"https://artifacthub.io/api/v1/packages/helm/loft/vcluster-rancher-operator",
"https://artifacthub.io/api/v1/packages/helm/log2rbac-operator/log2rbac-operator",
"https://artifacthub.io/api/v1/packages/helm/logging-operator/logging-operator",
"https://artifacthub.io/api/v1/packages/helm/lsst-sqre/strimzi-registry-operator",
"https://artifacthub.io/api/v1/packages/helm/lumigo-operator/lumigo-operator",
"https://artifacthub.io/api/v1/packages/helm/mariadb-operator/mariadb-operator",
"https://artifacthub.io/api/v1/packages/helm/mariadb-operator/mariadb-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/matrixone-operator/matrixone-operator",
"https://artifacthub.io/api/v1/packages/helm/mattermost/mattermost-operator",
"https://artifacthub.io/api/v1/packages/helm/mazin-ndb-operator/ndb-operator",
"https://artifacthub.io/api/v1/packages/helm/mdai-charts/mdai-operator",
"https://artifacthub.io/api/v1/packages/helm/mdai-charts/mydecisive-engine-operator",
"https://artifacthub.io/api/v1/packages/helm/mdai-charts/opentelemetry-operator",
"https://artifacthub.io/api/v1/packages/helm/meshery/meshery-operator",
"https://artifacthub.io/api/v1/packages/helm/mesosphere/kafka-operator",
"https://artifacthub.io/api/v1/packages/helm/mesosphere/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/mesosphere/postgres-operator",
"https://artifacthub.io/api/v1/packages/helm/mesosphere/prometheus-operator",
"https://artifacthub.io/api/v1/packages/helm/mesosphere-stable/kafka-operator",
"https://artifacthub.io/api/v1/packages/helm/mesosphere-stable/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/mesosphere-stable/logging-operator",
"https://artifacthub.io/api/v1/packages/helm/metadata-injector-operator/metadata-injector",
"https://artifacthub.io/api/v1/packages/helm/metakube/istio-operator",
"https://artifacthub.io/api/v1/packages/helm/milvus-operator/milvus-operator",
"https://artifacthub.io/api/v1/packages/helm/minio-operator/minio-operator",
"https://artifacthub.io/api/v1/packages/helm/minio-operator/operator",
"https://artifacthub.io/api/v1/packages/helm/mintel/aws-api-gateway-operator",
"https://artifacthub.io/api/v1/packages/helm/mmontes/cockroachdb-operator",
"https://artifacthub.io/api/v1/packages/helm/mmontes/echoperator",
"https://artifacthub.io/api/v1/packages/helm/mohammadne/operator-helm",
"https://artifacthub.io/api/v1/packages/helm/mojaloop/security-role-perm-operator-svc",
"https://artifacthub.io/api/v1/packages/helm/mongodb-helm-charts/community-operator",
"https://artifacthub.io/api/v1/packages/helm/mongodb-helm-charts/community-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/mongodb-helm-charts/enterprise-operator",
"https://artifacthub.io/api/v1/packages/helm/mongodb-helm-charts/mongodb-atlas-operator",
"https://artifacthub.io/api/v1/packages/helm/mongodb-helm-charts/mongodb-atlas-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/monosql-operator/eloq-operator",
"https://artifacthub.io/api/v1/packages/helm/monosql-operator/monograph-operator",
"https://artifacthub.io/api/v1/packages/helm/mysql-ndb-operator/ndb-operator",
"https://artifacthub.io/api/v1/packages/helm/mysql-operator/mysql-operator",
"https://artifacthub.io/api/v1/packages/helm/nats/nats-operator",
"https://artifacthub.io/api/v1/packages/helm/natz-operator/natz-operator",
"https://artifacthub.io/api/v1/packages/helm/netapp-trident/trident-operator",
"https://artifacthub.io/api/v1/packages/helm/netbox/netbox-operator",
"https://artifacthub.io/api/v1/packages/helm/netchecks/netchecks",
"https://artifacthub.io/api/v1/packages/helm/netobserv/netobserv-operator",
"https://artifacthub.io/api/v1/packages/helm/netrisai/netris-operator",
"https://artifacthub.io/api/v1/packages/helm/newsaktuell/keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/ngrok/ngrok-operator",
"https://artifacthub.io/api/v1/packages/helm/ngrok-operator/ngrok-operator",
"https://artifacthub.io/api/v1/packages/helm/nineinfra-charts/doris-operator",
"https://artifacthub.io/api/v1/packages/helm/nineinfra-charts/hdfs-operator",
"https://artifacthub.io/api/v1/packages/helm/nineinfra-charts/kyuubi-operator",
"https://artifacthub.io/api/v1/packages/helm/nineinfra-charts/metastore-operator",
"https://artifacthub.io/api/v1/packages/helm/nineinfra-charts/minio-operator",
"https://artifacthub.io/api/v1/packages/helm/nineinfra-charts/zookeeper-operator",
"https://artifacthub.io/api/v1/packages/helm/nn-co/base",
"https://artifacthub.io/api/v1/packages/helm/nn-co/base-job",
"https://artifacthub.io/api/v1/packages/helm/nodepulse/trivy-operator",
"https://artifacthub.io/api/v1/packages/helm/nutanix-helm-releases/altinity-clickhouse-operator",
"https://artifacthub.io/api/v1/packages/helm/nutanix/ndb-operator",
"https://artifacthub.io/api/v1/packages/helm/nvidia-gpu-operator/gpu-operator",
"https://artifacthub.io/api/v1/packages/helm/opencord/rook-operator",
"https://artifacthub.io/api/v1/packages/helm/open-feature-operator/open-feature-operator",
"https://artifacthub.io/api/v1/packages/helm/openinfradev/elasticsearch-operator",
"https://artifacthub.io/api/v1/packages/helm/openinfradev/fluentbit-operator",
"https://artifacthub.io/api/v1/packages/helm/openinfradev/fluent-operator",
"https://artifacthub.io/api/v1/packages/helm/openinfradev/istio-operator",
"https://artifacthub.io/api/v1/packages/helm/openinfradev/jaeger-operator",
"https://artifacthub.io/api/v1/packages/helm/openinfradev/k8ssandra-operator",
"https://artifacthub.io/api/v1/packages/helm/openinfradev/keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/openinfradev/keycloak-resources-deployment-for-keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/openresty-operator/openresty-operator",
"https://artifacthub.io/api/v1/packages/helm/opensearch-operator/opensearch-operator",
"https://artifacthub.io/api/v1/packages/helm/openshift-bootstraps/collection-management-operators",
"https://artifacthub.io/api/v1/packages/helm/openshift-bootstraps/collection-operators",
"https://artifacthub.io/api/v1/packages/helm/openshift-bootstraps/compliance-operator-full-stack",
"https://artifacthub.io/api/v1/packages/helm/openshift-bootstraps/file-integrity-operator",
"https://artifacthub.io/api/v1/packages/helm/openshift-bootstraps/helper-operator",
"https://artifacthub.io/api/v1/packages/helm/openshift-bootstraps/setup-container-security-operator",
"https://artifacthub.io/api/v1/packages/helm/openshift/ibm-operator-catalog-enablement",
"https://artifacthub.io/api/v1/packages/helm/openshift/rafay-operator-redhat",
"https://artifacthub.io/api/v1/packages/helm/opentelemetry-helm/opentelemetry-operator",
"https://artifacthub.io/api/v1/packages/helm/opsie/operator",
"https://artifacthub.io/api/v1/packages/helm/ot-container-kit/logging-operator",
"https://artifacthub.io/api/v1/packages/helm/ot-container-kit/mongodb-operator",
"https://artifacthub.io/api/v1/packages/helm/ot-container-kit/otel-operator",
"https://artifacthub.io/api/v1/packages/helm/ot-container-kit/redis-operator",
"https://artifacthub.io/api/v1/packages/helm/ovrclk-2/akash-hostname-operator",
"https://artifacthub.io/api/v1/packages/helm/ovrclk-2/akash-inventory-operator",
"https://artifacthub.io/api/v1/packages/helm/ovrclk-2/akash-ip-operator",
"https://artifacthub.io/api/v1/packages/helm/ovrclk/akash-hostname-operator",
"https://artifacthub.io/api/v1/packages/helm/ovrclk/akash-inventory-operator",
"https://artifacthub.io/api/v1/packages/helm/ovrclk/akash-ip-operator",
"https://artifacthub.io/api/v1/packages/helm/paganuzzi/ngrok-operator",
"https://artifacthub.io/api/v1/packages/helm/particuleio/istio-operator",
"https://artifacthub.io/api/v1/packages/helm/patch-operator/patch-operator",
"https://artifacthub.io/api/v1/packages/helm/percona/pg-operator",
"https://artifacthub.io/api/v1/packages/helm/percona/psmdb-operator",
"https://artifacthub.io/api/v1/packages/helm/percona/ps-operator",
"https://artifacthub.io/api/v1/packages/helm/percona/pxc-operator",
"https://artifacthub.io/api/v1/packages/helm/phppgadmin-helm/tweet-factory-operator",
"https://artifacthub.io/api/v1/packages/helm/piedeck/piedeck",
"https://artifacthub.io/api/v1/packages/helm/pingdom-operator/pingdom-operator",
"https://artifacthub.io/api/v1/packages/helm/pipeline-operator-dps0340-fork/pipeline-operator",
"https://artifacthub.io/api/v1/packages/helm/pipelinewise-operator/pipelinewise-operator",
"https://artifacthub.io/api/v1/packages/helm/pixie/pixie-operator-chart",
"https://artifacthub.io/api/v1/packages/helm/pixie/pixie-operator-helm2-chart",
"https://artifacthub.io/api/v1/packages/helm/pnnl-miscscripts/gitlab-runner-operator",
"https://artifacthub.io/api/v1/packages/helm/pnnl-miscscripts/tenant-namespace-operator",
"https://artifacthub.io/api/v1/packages/helm/portefaix-hub/grafana-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/portefaix-hub/prometheus-operator-mixin",
"https://artifacthub.io/api/v1/packages/helm/portefaix-hub/trivy-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/postgres-operator/postgres-operator",
"https://artifacthub.io/api/v1/packages/helm/postgres-operator-ui/postgres-operator-ui",
"https://artifacthub.io/api/v1/packages/helm/pragmatik-analytics/pragmatik-analytics",
"https://artifacthub.io/api/v1/packages/helm/projectcalico/tigera-operator",
"https://artifacthub.io/api/v1/packages/helm/projectcapsule/capsule",
"https://artifacthub.io/api/v1/packages/helm/projectcapsule/capsule-proxy",
"https://artifacthub.io/api/v1/packages/helm/prometheus-community/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/prometheus-community/prometheus-druid-exporter",
"https://artifacthub.io/api/v1/packages/helm/prometheus-community/prometheus-operator-admission-webhook",
"https://artifacthub.io/api/v1/packages/helm/prometheus-community/prometheus-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/prometheus-worawutchan/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/prometheus-worawutchan/prometheus-druid-exporter",
"https://artifacthub.io/api/v1/packages/helm/pulumi-kubernetes-operator/pulumi-kubernetes-operator",
"https://artifacthub.io/api/v1/packages/helm/punchplatform/operator",
"https://artifacthub.io/api/v1/packages/helm/punchplatform/operator-crds",
"https://artifacthub.io/api/v1/packages/helm/quarks/cf-operator",
"https://artifacthub.io/api/v1/packages/helm/rabbitmq-cluster-operator/rabbitmq-cluster-operator",
"https://artifacthub.io/api/v1/packages/helm/rancher-charts/rancher-aks-operator",
"https://artifacthub.io/api/v1/packages/helm/rancher-charts/rancher-aks-operator-crd",
"https://artifacthub.io/api/v1/packages/helm/rancher-charts/rancher-eks-operator",
"https://artifacthub.io/api/v1/packages/helm/rancher-charts/rancher-eks-operator-crd",
"https://artifacthub.io/api/v1/packages/helm/rancher-charts/rancher-gke-operator",
"https://artifacthub.io/api/v1/packages/helm/rancher-charts/rancher-gke-operator-crd",
"https://artifacthub.io/api/v1/packages/helm/rancher-charts/rancher-monitoring",
"https://artifacthub.io/api/v1/packages/helm/rancher-charts/ui-plugin-operator",
"https://artifacthub.io/api/v1/packages/helm/rancher-charts/ui-plugin-operator-crd",
"https://artifacthub.io/api/v1/packages/helm/raven-operator/raven-operator",
"https://artifacthub.io/api/v1/packages/helm/redhat-cop/argocd-operator",
"https://artifacthub.io/api/v1/packages/helm/redhat-cop/gitops-operator",
"https://artifacthub.io/api/v1/packages/helm/redhat-cop/helper-operator",
"https://artifacthub.io/api/v1/packages/helm/redhat-cop/operatorhub",
"https://artifacthub.io/api/v1/packages/helm/redhat-cop/operators-installer",
"https://artifacthub.io/api/v1/packages/helm/redhat/ibm-operator-catalog-enablement",
"https://artifacthub.io/api/v1/packages/helm/redis-enterprise-operator-official/redis-enterprise-operator",
"https://artifacthub.io/api/v1/packages/helm/redis-enterprise-operator/redis-enterprise-operator",
"https://artifacthub.io/api/v1/packages/helm/redis-operator/redis-operator",
"https://artifacthub.io/api/v1/packages/helm/redpanda-data/operator",
"https://artifacthub.io/api/v1/packages/helm/redpanda/redpanda-operator",
"https://artifacthub.io/api/v1/packages/helm/resource-manager-operator/resource-manager-operator",
"https://artifacthub.io/api/v1/packages/helm/reverse-vault-secret-operator/reverse-vault-secret-operator",
"https://artifacthub.io/api/v1/packages/helm/rhio/rhio-operator",
"https://artifacthub.io/api/v1/packages/helm/riftbit/rabbitmq-cluster-operator",
"https://artifacthub.io/api/v1/packages/helm/riotkit-org/git-clone-operator",
"https://artifacthub.io/api/v1/packages/helm/rock8s/easy-olm-operator",
"https://artifacthub.io/api/v1/packages/helm/rock8s/gitlab-operator",
"https://artifacthub.io/api/v1/packages/helm/rock8s/integration-operator",
"https://artifacthub.io/api/v1/packages/helm/rock8s/kanister-operator",
"https://artifacthub.io/api/v1/packages/helm/rock8s/operator-minio",
"https://artifacthub.io/api/v1/packages/helm/rock8s/resource-binding-operator",
"https://artifacthub.io/api/v1/packages/helm/rocket-gpu/gpu-operator",
"https://artifacthub.io/api/v1/packages/helm/romholdings/devtron-operator",
"https://artifacthub.io/api/v1/packages/helm/romholdings/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/rookout/operator",
"https://artifacthub.io/api/v1/packages/helm/sagikazarmark/rabbitmq-operator",
"https://artifacthub.io/api/v1/packages/helm/salaboy/knative-helm-operator",
"https://artifacthub.io/api/v1/packages/helm/schichtel/keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/schichtel/keycloak-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/securecodebox/auto-discovery-kubernetes",
"https://artifacthub.io/api/v1/packages/helm/securecodebox/operator",
"https://artifacthub.io/api/v1/packages/helm/seldon/seldon-core-operator",
"https://artifacthub.io/api/v1/packages/helm/service-binding-operator-helm-chart/service-binding-operator",
"https://artifacthub.io/api/v1/packages/helm/shardingsphere/apache-shardingsphere-operator-charts",
"https://artifacthub.io/api/v1/packages/helm/shardingsphere/apache-shardingsphere-operator-cluster-charts",
"https://artifacthub.io/api/v1/packages/helm/shulker-operator/shulker-operator",
"https://artifacthub.io/api/v1/packages/helm/skyloud-helm-charts/tailscale-operator",
"https://artifacthub.io/api/v1/packages/helm/slamdev/altinity-clickhouse-operator",
"https://artifacthub.io/api/v1/packages/helm/slamdev/external-secrets-operator",
"https://artifacthub.io/api/v1/packages/helm/softonic/eck-operator",
"https://artifacthub.io/api/v1/packages/helm/softonic/keda-operator",
"https://artifacthub.io/api/v1/packages/helm/softonic/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/softonic/rate-limit-operator",
"https://artifacthub.io/api/v1/packages/helm/softonic/redis-operator",
"https://artifacthub.io/api/v1/packages/helm/softonic/service-level-operator",
"https://artifacthub.io/api/v1/packages/helm/softonic/trivy-operator",
"https://artifacthub.io/api/v1/packages/helm/someblackmagic/banzaicloud-logging-operator-monitoring",
"https://artifacthub.io/api/v1/packages/helm/sops-operator/sops-operator",
"https://artifacthub.io/api/v1/packages/helm/sops-secrets-operator/sops-secrets-operator",
"https://artifacthub.io/api/v1/packages/helm/spark-kubernetes-operator/spark-kubernetes-operator",
"https://artifacthub.io/api/v1/packages/helm/sql-operator/sql-operator",
"https://artifacthub.io/api/v1/packages/helm/sstarcher/newrelic-operator",
"https://artifacthub.io/api/v1/packages/helm/stackgres-charts/stackgres-operator",
"https://artifacthub.io/api/v1/packages/helm/stakater/jira-service-desk-operator",
"https://artifacthub.io/api/v1/packages/helm/stakater/mattermost-operator",
"https://artifacthub.io/api/v1/packages/helm/stakater/minio-operator",
"https://artifacthub.io/api/v1/packages/helm/stakater/namespace-configuration-operator",
"https://artifacthub.io/api/v1/packages/helm/stakater/prometheus-operator",
"https://artifacthub.io/api/v1/packages/helm/stakater/slack-operator",
"https://artifacthub.io/api/v1/packages/helm/stakater/splunk-operator",
"https://artifacthub.io/api/v1/packages/helm/stakater/stakater-tenant-operator",
"https://artifacthub.io/api/v1/packages/helm/stakater/tenant-operator",
"https://artifacthub.io/api/v1/packages/helm/stakater/tenant-operator-crd",
"https://artifacthub.io/api/v1/packages/helm/stakater/workshop-operator",
"https://artifacthub.io/api/v1/packages/helm/stakewise/operator",
"https://artifacthub.io/api/v1/packages/helm/stakewise/operator-effectiveness",
"https://artifacthub.io/api/v1/packages/helm/stakewise/v3-operator",
"https://artifacthub.io/api/v1/packages/helm/startx/chaos",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-3scale",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-acm",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-acs",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-ansible",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-argocd",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-certmanager",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-compliance",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-config",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-console",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-costs",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-couchbase",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-descheduler",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-devworkspaces",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-dvo",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-gitlab",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-gitlab-runner",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-gpu",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-istio",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-jenkins",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-kafka",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-kepler",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-knative",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-kubecost",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-kubevirt",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-localstorage",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-logging",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-maintenance",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-metering",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-mtc",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-mtr",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-mtv",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-mustgather",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-nexus",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-nfd",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-odf",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-ods",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-pipeline",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-ptp",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-quay",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-redis",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-sso",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-storage-efs",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-vault",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-vault-config",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-vpa",
"https://artifacthub.io/api/v1/packages/helm/startx/cluster-workspace",
"https://artifacthub.io/api/v1/packages/helm/startx/operator",
"https://artifacthub.io/api/v1/packages/helm/statcan/argocd-operator",
"https://artifacthub.io/api/v1/packages/helm/statcan/fluentd-operator",
"https://artifacthub.io/api/v1/packages/helm/statcan/minio-operator",
"https://artifacthub.io/api/v1/packages/helm/statcan/prometheus-operator",
"https://artifacthub.io/api/v1/packages/helm/statcan/solr-operator",
"https://artifacthub.io/api/v1/packages/helm/statcan/starboard-operator",
"https://artifacthub.io/api/v1/packages/helm/stevehipwell-helm-charts-tigera-operator/tigera-operator",
"https://artifacthub.io/api/v1/packages/helm/stevehipwell/tigera-operator",
"https://artifacthub.io/api/v1/packages/helm/storageos/storageos-operator",
"https://artifacthub.io/api/v1/packages/helm/streamnative/pulsar-operator",
"https://artifacthub.io/api/v1/packages/helm/streamnative/pulsar-resources-operator",
"https://artifacthub.io/api/v1/packages/helm/streamnative/sn-operator",
"https://artifacthub.io/api/v1/packages/helm/strimzi-kafka-operator/strimzi-kafka-operator",
"https://artifacthub.io/api/v1/packages/helm/strimzi/strimzi-kafka-operator",
"https://artifacthub.io/api/v1/packages/helm/strimzi-topic-operator/strimzi-topic-operator",
"https://artifacthub.io/api/v1/packages/helm/strrl-helm/cloudflare-tunnel-ingress-controller",
"https://artifacthub.io/api/v1/packages/helm/stunner/stunner-gateway-operator",
"https://artifacthub.io/api/v1/packages/helm/stunner/stunner-gateway-operator-dev",
"https://artifacthub.io/api/v1/packages/helm/supporttools/do-operator",
"https://artifacthub.io/api/v1/packages/helm/symfony-operator/symfony-operator",
"https://artifacthub.io/api/v1/packages/helm/tailing-sidecar-operator/tailing-sidecar-operator",
"https://artifacthub.io/api/v1/packages/helm/tailscale/tailscale-operator",
"https://artifacthub.io/api/v1/packages/helm/teleport-agent-kube/teleport-operator",
"https://artifacthub.io/api/v1/packages/helm/terraform-controller/terraform-controller",
"https://artifacthub.io/api/v1/packages/helm/traefik-external-dns-operator/traefik-external-dns-operator",
"https://artifacthub.io/api/v1/packages/helm/tremolo/openunison-operator",
"https://artifacthub.io/api/v1/packages/helm/trivy-operator-polr-adapter/trivy-operator-polr-adapter",
"https://artifacthub.io/api/v1/packages/helm/trivy-operator/starboard-operator",
"https://artifacthub.io/api/v1/packages/helm/trivy-operator/trivy-operator",
"https://artifacthub.io/api/v1/packages/helm/truefoundry/clickhouse-operator",
"https://artifacthub.io/api/v1/packages/helm/truefoundry/tfy-gpu-operator",
"https://artifacthub.io/api/v1/packages/helm/truefoundry/tfy-inferentia-operator",
"https://artifacthub.io/api/v1/packages/helm/tyk-helm/tyk-operator",
"https://artifacthub.io/api/v1/packages/helm/unionoperator/union-operator",
"https://artifacthub.io/api/v1/packages/helm/upwind/upwind-operator",
"https://artifacthub.io/api/v1/packages/helm/utho-operator/utho-app-operator-chart",
"https://artifacthub.io/api/v1/packages/helm/vald/vald-benchmark-operator",
"https://artifacthub.io/api/v1/packages/helm/vald/vald-helm-operator",
"https://artifacthub.io/api/v1/packages/helm/vals-operator/vals-operator",
"https://artifacthub.io/api/v1/packages/helm/vault-config-operator/vault-config-operator",
"https://artifacthub.io/api/v1/packages/helm/vault-operator/vault-operator",
"https://artifacthub.io/api/v1/packages/helm/vertica-charts/verticadb-operator",
"https://artifacthub.io/api/v1/packages/helm/victoriametrics/victoria-metrics-distributed",
"https://artifacthub.io/api/v1/packages/helm/victoriametrics/victoria-metrics-k8s-stack",
"https://artifacthub.io/api/v1/packages/helm/victoriametrics/victoria-metrics-operator",
"https://artifacthub.io/api/v1/packages/helm/victoriametrics/victoria-metrics-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/vineyard/vineyard-operator",
"https://artifacthub.io/api/v1/packages/helm/webhookrelay-operator/webhookrelay-operator",
"https://artifacthub.io/api/v1/packages/helm/wener/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/wener/logging-operator",
"https://artifacthub.io/api/v1/packages/helm/wenerme/kube-prometheus-stack",
"https://artifacthub.io/api/v1/packages/helm/wenerme/logging-operator",
"https://artifacthub.io/api/v1/packages/helm/wenerme/minio-operator",
"https://artifacthub.io/api/v1/packages/helm/wenerme/postgres-operator",
"https://artifacthub.io/api/v1/packages/helm/wenerme/postgres-operator-ui",
"https://artifacthub.io/api/v1/packages/helm/wenerme/victoria-metrics-k8s-stack",
"https://artifacthub.io/api/v1/packages/helm/wenerme/victoria-metrics-operator",
"https://artifacthub.io/api/v1/packages/helm/wener/minio-operator",
"https://artifacthub.io/api/v1/packages/helm/wener/postgres-operator",
"https://artifacthub.io/api/v1/packages/helm/wener/postgres-operator-ui",
"https://artifacthub.io/api/v1/packages/helm/wener/victoria-metrics-k8s-stack",
"https://artifacthub.io/api/v1/packages/helm/wener/victoria-metrics-operator",
"https://artifacthub.io/api/v1/packages/helm/wikimedia/flink-kubernetes-operator",
"https://artifacthub.io/api/v1/packages/helm/wikimedia/flink-kubernetes-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/wikimedia/spark-operator",
"https://artifacthub.io/api/v1/packages/helm/wiremind/gpu-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/wiremind/istio-operator",
"https://artifacthub.io/api/v1/packages/helm/wiremind/istio-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/wiremind/keycloak-operator",
"https://artifacthub.io/api/v1/packages/helm/wiremind/keycloak-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/wiremind/postgres-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/wiremind/silence-operator",
"https://artifacthub.io/api/v1/packages/helm/wiremind/silence-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/wiremind/trivy-operator-crds",
"https://artifacthub.io/api/v1/packages/helm/wordpressmysql/wordpress-mysql",
"https://artifacthub.io/api/v1/packages/helm/wyrihaximusnet/redis-db-assignment-operator",
"https://artifacthub.io/api/v1/packages/helm/xxl-job-admin/kadalu-operator",
"https://artifacthub.io/api/v1/packages/helm/ymatrix/matrixdb-operator",
"https://artifacthub.io/api/v1/packages/helm/youniqx-oss/heist",
"https://artifacthub.io/api/v1/packages/helm/zalando-postgres-operator/postgres-operator",
"https://artifacthub.io/api/v1/packages/helm/zelic-io/cloudflare-zero-trust-operator",
]

def fetch_chart_data(url: str) -> dict:
    """Fetch JSON data from the given URL with exponential backoff for rate limiting."""
    max_retries = 5
    base_delay = 2  # seconds

    for attempt in range(max_retries):
        try:
            response = requests.get(url)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.HTTPError as e:
            if e.response.status_code == 429 and attempt < max_retries - 1:
                delay = base_delay * (2 ** attempt)  # Exponential backoff
                print(f"Rate limited for {url}. Retrying in {delay} seconds...")
                time.sleep(delay)
            else:
                print(f"Error fetching {url}: {e}")
                return None
        except requests.exceptions.RequestException as e:
            print(f"Error fetching {url}: {e}")
            return None

def is_high_quality_chart(data: dict) -> bool:
    """
    Applies a set of rules to determine if a chart is high-quality and worth tracking.

    Returns:
        bool: True if the chart passes all checks, False otherwise.
    """
    chart_name = data.get('name', 'Unknown')

    # --- Rule 1: Hard Rejections (must-pass criteria) ---

    # Reject if deprecated
    if data.get('deprecated', False):
        print(f"  - [SKIP] Chart '{chart_name}' is deprecated.")
        return False

    # Reject if the latest version is a pre-release (e.g., alpha, beta, rc)
    # You can comment this out if you want to track pre-releases.
    if data.get('prerelease', False):
        print(f"  - [SKIP] Chart '{chart_name}' latest version is a pre-release.")
        return False

    # Reject if the chart hasn't been updated in over a year
    max_age_days = 365
    last_update_ts = data.get('ts')
    if last_update_ts:
        last_update_dt = datetime.fromtimestamp(last_update_ts, tz=timezone.utc)
        age = datetime.now(timezone.utc) - last_update_dt
        if age.days > max_age_days:
            print(f"  - [SKIP] Chart '{chart_name}' has not been updated in {age.days} days (older than {max_age_days} days).")
            return False
    else:
        print(f"  - [SKIP] Chart '{chart_name}' has no timestamp information.")
        return False

    # --- Rule 2: Quality Scoring (flexible criteria) ---
    # The chart must accumulate enough points to be considered high-quality.

    quality_score = 0
    minimum_score_to_pass = 3

    # Score based on publisher reputation
    if data.get('repository', {}).get('verified_publisher', False):
        quality_score += 2
    if data.get('repository', {}).get('official', False):
        quality_score += 2

    # Score based on security and completeness
    if data.get('signed', False):
        quality_score += 2
    if data.get('has_values_schema', False):
        quality_score += 1
    if data.get('has_changelog', False):
        quality_score += 1

    # Score based on social proof and accountability
    if data.get('production_organizations_count', 0) > 0:
        quality_score += 1
    if data.get('maintainers'):
        quality_score += 1

    if quality_score < minimum_score_to_pass:
        print(f"  - [SKIP] Chart '{chart_name}' failed quality check with score {quality_score} (minimum is {minimum_score_to_pass}).")
        return False

    print(f"  - [PASS] Chart '{chart_name}' passed with quality score {quality_score}.")
    return True

def process_charts() -> Dict[str, dict]:
    """Process all chart URLs and group the high-quality ones by repository."""
    repositories = defaultdict(lambda: {'charts': []})

    for url in URLs:
        print(f"Processing {url}")
        data = fetch_chart_data(url)

        # Add a small delay to avoid overwhelming the API
        time.sleep(1)

        if not data:
            print(f"  - [SKIP] Could not fetch data for {url}")
            continue

        repo_name = data.get('repository', {}).get('name')
        repo_url = data.get('repository', {}).get('url')
        chart_name = data.get('name')

        if not all([repo_name, repo_url, chart_name]):
            print(f"  - [SKIP] Missing required repository/chart name for {url}")
            continue

        # Apply the quality filter
        if not is_high_quality_chart(data):
            # The reason for skipping is printed inside the helper function
            continue

        # If we reach here, the chart is worth tracking
        if 'url' not in repositories[repo_name]:
            repositories[repo_name]['url'] = repo_url
            repositories[repo_name]['name'] = repo_name

        keywords = data.get('keywords', [])
        repositories[repo_name]['charts'].append({
          'name': chart_name,
          'keywords': keywords,
        })

    return dict(repositories) # Convert back to a regular dict for the final output

def generate_yaml(repositories: Dict[str, dict]) -> None:
    """Generate the operators.yaml file from the processed data."""
    # Convert defaultdict to regular dict for yaml dumping
    yaml_data = list(repositories.values())

    # Write to operators.yaml
    with open('operators.yaml', 'w') as f:
        yaml.safe_dump(yaml_data, f, sort_keys=False, allow_unicode=True)

def main():
    print("Fetching and processing chart data...")
    repositories = process_charts()
    print("Generating operators.yaml...")
    generate_yaml(repositories)
    print("Done!")

if __name__ == "__main__":
    main()

