baseURL = '/'
languageCode = 'en-us'
title = 'RBAC ATLAS'
theme = 'terminal'


[params]
  author = "Lenin Alevski"
  description = "Software Engineering and Information Security"
  favicon = "/favicon.png"

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "charts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = false

[params.twitter]
  creator = "alevsk"
  site = "alevsk"

[languages]
  [languages.en]
    languageName = "English"
    title = "RBAC ATLAS"

    [languages.en.params]
      subtitle = "A Curated Index of RBAC Policies in Kubernetes"
      owner = "Lenin Alevski"
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "🔗 See Details"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer entries"
      olderPosts = "Older entries"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "RBAC ATLAS"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "all-categories"
          name = "All Categories"
          url = "/categories/"
        [[languages.en.menu.main]]
          identifier = "all-risks"
          name = "All Risks"
          url = "/tags/"
