baseURL = 'https://6964-73-222-202-255.ngrok-free.app/'
languageCode = 'en-us'
title = 'RBAC ATLAS'
theme = 'terminal'

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "charts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = true

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  Toc = false

[params.twitter]
  creator = "alevsk"
  site = "alevsk"

[languages]
  [languages.en]
    languageName = "English"
    title = "RBAC ATLAS"

    [languages.en.params]
      subtitle = "A curated database of RBAC policies used by popular Kubernetes Operators, with security annotations highlighting their permissions, potential risks, and abuse scenarios."
      owner = "Lenin Alevski"
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "🔗 See Details"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "RBAC ATLAS"
        logoHomeLink = "/"
