name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Install dependencies
        run: make install

      - name: Run linting
        run: make lint

      # - name: Run tests
      #   run: make test

      - name: Build site
        run: make build

      - name: Build Docker image
        run: make docker

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag rbac-atlas:latest ${{ secrets.DOCKERHUB_USERNAME }}/rbac-atlas:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rbac-atlas:latest
